- name: "example playbook on variables"
  hosts: all
  vars:
    URL: play.url.com
  tasks:
    - name: "task1 "
      ansible.builtin.debug:
        msg: play level task 1 URL - {{ URL }}
    - name: "task2"
      ansible.builtin.debug:
        msg: play level task2 URL - {{ URL }}

